[toc]

# Pytorch 使用过程中的一些函数记录

In [2]:
import torch

## Tensor.bmm

batch matrix multiply

In [9]:
import torch

x = torch.randn([10,4,3])
y = torch.randn([10,3,2])
z = x.bmm(y)
z.shape # [10, 4, 3] x [10 ,3, 2] -> [10 ,4, 2]

torch.Size([10, 4, 2])

## torch.multinomial

返回一个满足给定概率分布的一个多项分布的抽样。

In [18]:
prob = torch.Tensor([0, 999, 123, 0]) # 这个概率分布没有归一化，在 torch.multinomial 会自动归一化
torch.multinomial(prob, 10, replacement=True)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## torch.max

DataLoader 需要指定 cpu 的线程数。一般指定与核数相同的，可以使用下面的命令得到 cpu 的核数

In [ ]:
import multiprocessing
multiprocessing.cpu_count()

## 常数 tensor

`shape=()` 时可以生成一个常数tensor。使用 `.item()` 可以从这个tensor中取出数字

In [10]:
b = torch.zeros(())
b.item() # 0

0.0

## torch.max

torch.max 有多个重载版本。其中最常见的是 

In [9]:
yhat = torch.randn(2, 10)
torch.max(yhat, axis=1)

torch.return_types.max(
values=tensor([1.3190, 2.2014]),
indices=tensor([1, 5]))

上面的不但可以返回 yhat 沿 axis=1 的最大值，还可以返回最大值所对应的下标！

## torch.repeat

In [14]:
x = torch.randint(4, (1, 2, 3))
print(x)
x.repeat(2, 3, 1) # 沿0轴重复2次，沿1轴重复3次，沿2轴不重复

tensor([[[2, 2, 2],
         [3, 1, 0]]])


tensor([[[2, 2, 2],
         [3, 1, 0],
         [2, 2, 2],
         [3, 1, 0],
         [2, 2, 2],
         [3, 1, 0]],

        [[2, 2, 2],
         [3, 1, 0],
         [2, 2, 2],
         [3, 1, 0],
         [2, 2, 2],
         [3, 1, 0]]])

如果想让 x 沿 0 轴重复2次，不能用 `x.repeat(2)`，而得用

In [16]:
x.repeat(2, 1, 1)

tensor([[[2, 2, 2],
         [3, 1, 0]],

        [[2, 2, 2],
         [3, 1, 0]]])

## torch.tranpose()

这个和 np.transpose 不同。这个每次只能调换两个维度的顺序。

In [18]:
x = torch.randn(3, 4, 2)
print(x.transpose(0, 1).shape)

torch.Size([4, 3, 2])
