[toc]

# Tensorflow1 dataset

tensorflow1 和 tensorflow2 的 dataset 的用法略有不同，这里是 tensorflow1 中的 dataset 的用法


In [15]:
import tensorflow as tf

print(tf.__version__)

1.15.0


## tf.data.Dataset.from_tensor_slices

这个可以将 tensor 转化为 dataset

## dataset.padded_batch

In [21]:
import tensorflow as tf
import numpy as np

tf.reset_default_graph()

x = [[1, 0, 0], [2, 3, 0], [4, 5, 5], [7, 8, 0], [9, 0, 0], [0, 1, 0]]

#tf.TensorShape([])     表示长度为单个数字
#tf.TensorShape([None]) 表示不 padding
padded_shapes = tf.TensorShape([4]) # 指将一个 instance padding 成形状为 [4] 的

dataset = tf.data.Dataset.from_tensor_slices(x)
dataset = dataset.padded_batch(2, padded_shapes=padded_shapes)
iterator = dataset.make_one_shot_iterator()
next_batch = iterator.get_next()

with tf.Session() as sess:
    try:
        while True:
            print(sess.run(next_batch))
    except tf.errors.OutOfRangeError:
        print("end")

[[1 0 0 0]
 [2 3 0 0]]
[[4 5 5 0]
 [7 8 0 0]]
[[9 0 0 0]
 [0 1 0 0]]
end
