[toc]

# Pytorch Reshape

In [2]:
import torch 
import numpy as np 

In [3]:
x = torch.Tensor([1,2,3,4])

## Tensor.view([2,2])

In [6]:
x.view([2,2])

tensor([[1., 2.],
        [3., 4.]])

## Tensor.reshape([2,2])

In [8]:
x.reshape([2,2])

tensor([[1., 2.],
        [3., 4.]])

## 添加一个维度

### Tensor.unsqueeze

In [12]:
x.unsqueeze(0)

tensor([[1., 2., 3., 4.]])

In [11]:
x.unsqueeze(1)

tensor([[1.],
        [2.],
        [3.],
        [4.]])

### np.newaxis

In [13]:
x[np.newaxis, :]

tensor([[1., 2., 3., 4.]])

In [14]:
x[:, np.newaxis]

tensor([[1.],
        [2.],
        [3.],
        [4.]])

## 删除一个维度

### Tensor.squeeze

In [18]:
x = torch.zeros([1,2,1,3])

In [20]:
x.squeeze().shape

torch.Size([2, 3])