[toc]

# Tensorflow often

In [8]:
import tensorflow as tf
import numpy as np

x = tf.placeholder(tf.float32, [None, 10, 2])
prob = tf.nn.softmax(x)
predictions = tf.argmax(prob,
                      axis=-1,
                      output_type=tf.int32)
confidence = tf.reduce_max(prob, axis=-1)
with tf.Session() as sess:
    print(sess.run([x, prob, predictions, confidence], feed_dict={x: np.random.randn(1, 10, 2)}))

[array([[[-2.224313  ,  0.9633124 ],
        [ 1.7856361 ,  0.21030359],
        [-0.8858109 , -1.1038158 ],
        [-0.6865347 , -0.03186231],
        [ 0.12354209,  0.49452102],
        [-1.2486702 ,  0.279794  ],
        [ 0.04500024,  0.07425252],
        [ 1.530206  , -2.0825903 ],
        [-0.63266194,  1.1967527 ],
        [-0.41521698,  0.8308603 ]]], dtype=float32), array([[[0.03963406, 0.9603659 ],
        [0.8285425 , 0.17145753],
        [0.5542864 , 0.44571364],
        [0.3419374 , 0.6580626 ],
        [0.40830448, 0.5916955 ],
        [0.17821848, 0.82178146],
        [0.49268743, 0.50731254],
        [0.97373223, 0.0262677 ],
        [0.13830803, 0.861692  ],
        [0.22337992, 0.7766201 ]]], dtype=float32), array([[1, 0, 0, 1, 1, 1, 1, 0, 1, 1]], dtype=int32), array([[0.9603659 , 0.8285425 , 0.5542864 , 0.6580626 , 0.5916955 ,
        0.82178146, 0.50731254, 0.97373223, 0.861692  , 0.7766201 ]],
      dtype=float32)]


## tf.gather 取下标

In [9]:
import tensorflow as tf
import numpy as np

random_x = np.random.randn(5, 2)
x = tf.placeholder(tf.float32, [None, 2])
gathered_x = tf.gather(x, [0,1]) # 取 0，1行
gathered_y = tf.gather(x, [0,1], axis=1) # 取 0,1 列
with tf.Session() as sess:
    print(sess.run(x, feed_dict={x: random_x}))
    print(sess.run(gathered_x, feed_dict={x: random_x}))
    print(sess.run(gathered_y, feed_dict={x: random_x}))

[[ 0.85639054 -0.10171583]
 [-0.6418337   1.2410208 ]
 [-1.0488756  -1.1425829 ]
 [-0.7236162   0.02785115]
 [-0.64129376 -0.22735468]]
[[ 0.85639054 -0.10171583]
 [-0.6418337   1.2410208 ]]
[[ 0.85639054 -0.10171583]
 [-0.6418337   1.2410208 ]
 [-1.0488756  -1.1425829 ]
 [-0.7236162   0.02785115]
 [-0.64129376 -0.22735468]]


## tf.linalg.band_part

作用：主要功能是以对角线为中心，取它的副对角线部分，其他部分用0填充。
- input:输入的张量.
- num_lower:下三角矩阵保留的副对角线数量，从主对角线开始计算，相当于下三角的带宽。取值为负数时，则全部保留。
- num_upper:上三角矩阵保留的副对角线数量，从主对角线开始计算，相当于上三角的带宽。取值为负数时，则全部保留。

之前的函数是 `tf.matrix_band_part`，现在是 `tf.linalg.band_part`

In [67]:
x = tf.placeholder(tf.int32, [None, 4])

inputs = np.ones((4,4))

with tf.Session() as sess:
    # 下三角不保留，上三角不保留（因此是个对角矩阵）
    ret = sess.run(tf.linalg.band_part(x, 0, 0), feed_dict={x: inputs})
    print(ret)
    
    # 下三角保留一个行，上三角全保留
    ret = sess.run(tf.linalg.band_part(x, 1, -1), feed_dict={x: inputs})
    print(ret)
    
    # 下三角保留两个，上三角保留两个
    ret = sess.run(tf.linalg.band_part(x, 2, 2), feed_dict={x: inputs})
    print(ret)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 1 1 1]
 [1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]]
[[1 1 1 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 1 1 1]]


In [2]:
import tensorflow as tf

seq_length=3
with tf.Session() as sess:
    down_left = tf.linalg.band_part(
      tf.ones((seq_length, seq_length)),
      0,
      -1)

    print(sess.run(down_left))

/opt/anaconda3/envs/tars/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/anaconda3/envs/tars/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/anaconda3/envs/tars/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/anaconda3/envs/tars/lib/python3.7/site-packages/tensorflow/python/frame

[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]


/opt/anaconda3/envs/tars/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/anaconda3/envs/tars/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/anaconda3/envs/tars/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/anaconda3/envs/tars/lib/python3.7/site-packages/te

In [14]:
# to mask is the key tensor mask

batch_size = 3
from_seq_len = to_seq_len = 4

from_tensor = tf.placeholder(tf.int32, [batch_size, from_seq_len])
to_mask_placeholder = tf.placeholder(tf.int32, [batch_size, to_seq_len])

to_mask = tf.cast(
  tf.reshape(to_mask_placeholder, [batch_size, 1, to_seq_len]), tf.float32)

# to tile mask
broadcast_ones = tf.ones(
    shape=[batch_size, from_seq_len, 1], 
    dtype=tf.float32
)
# shape [batch_size, from_seq_length, to_seq_length]
mask = broadcast_ones * to_mask

with tf.Session() as sess:
    ret = sess.run(mask, feed_dict={
        from_tensor: [[0,-1,-1,-1], [0,2,-1,-1], [1,2,0,-1]], 
        to_mask_placeholder: [[1,0,0,0],[1,1,0,0],[1,1,1,0]]})
    print(ret)
    print(ret.shape)

[[[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 1. 0. 0.]
  [1. 1. 0. 0.]
  [1. 1. 0. 0.]
  [1. 1. 0. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]]
(3, 4, 4)


## tf.sign 返回结果的符号矩阵

In [25]:
import numpy as np

x = tf.placeholder(tf.float32, [None, None])
with tf.Session() as sess:
    ret = sess.run(tf.sign(x), feed_dict={x: np.random.randn(5, 5)})
    print(ret)

[[ 1. -1. -1. -1. -1.]
 [ 1.  1. -1.  1. -1.]
 [ 1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.]
 [ 1. -1.  1.  1.  1.]]


## tf.tile

`tile()` 平铺之意，用于在同一维度上的复制

In [28]:
with tf.Session() as sess:
    a = tf.constant([1,2],name='a') 
    b = tf.tile(a,[3])
    print(sess.run(b))

[1 2 1 2 1 2]


In [29]:
with tf.Session() as sess:
    a = tf.constant([[1,2],[3,4]], name='a') 
    b = tf.tile(a, [2, 4])
    print(sess.run(b))

[[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


## tf.matmul

In [57]:
x = tf.constant([[1,2],[3,4]]) # 2x2
y = tf.constant([[1],[2]]) # 2 x 1

with tf.Session() as sess:
    ret = sess.run(tf.matmul(x, y))
    print(ret )

[[ 5]
 [11]]


transpose_b 参数

In [56]:
x = tf.constant([[1,2],[3,4]]) # 2x2
y = tf.constant([[1,2]]) # 1 x 2

with tf.Session() as sess:
    ret = sess.run(tf.matmul(x, y, transpose_b=True))
    print(ret )

[[ 5]
 [11]]


# References
1. [tf.tile() 用法介绍_AI_盲的博客-CSDN博客](https://blog.csdn.net/xwd18280820053/article/details/72867818)