In [46]:
import tensorflow as tf 
x = tf.zeros([3, 2])
x[0][0] = 1

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [32]:
y = tf.Variable(tf.zeros([3, 2]))


<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[2., 2.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [47]:
y[:, 1].assign([1,2,3])

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[1., 1.],
       [0., 2.],
       [0., 3.]], dtype=float32)>

In [50]:
y[0, 0].assign(1)

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[1., 1.],
       [0., 2.],
       [0., 3.]], dtype=float32)>

In [37]:
y[0, 0:1].assign([1])

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[1., 2.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

注意不能使用下面的形式, 因为 y[0][0] 返回的是一个数。而 y[0][0:1] 返回的是一个 array

In [53]:
y[0][0].assign(1)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

因为 `y[0][0]` 返回的是一个 Tensor