[toc]

# Tensorflow softmax

softmax 默认是 axis=-1，也就是沿着最后一个轴进行归一化

In [9]:
import tensorflow as tf

x = tf.random.normal(shape=(3,2,5))
probs = tf.nn.softmax(x)

with tf.Session() as sess:
    probs_val = sess.run(probs)
    print(probs_val)

[[[0.26129097 0.07009715 0.18378055 0.45952004 0.02531134]
  [0.07223184 0.6171149  0.08543482 0.03298499 0.19223341]]

 [[0.3043427  0.07308506 0.01904083 0.5916134  0.01191791]
  [0.25839034 0.29768854 0.13115658 0.28711978 0.02564478]]

 [[0.50265723 0.10258091 0.32757312 0.04472334 0.02246547]
  [0.1978573  0.16254538 0.0957991  0.4310247  0.11277357]]]


In [11]:
probs_val.sum(axis=-1)

array([[1.       , 0.9999999],
       [0.9999999, 1.       ],
       [1.0000001, 1.       ]], dtype=float32)