[toc]

# Tensorflow crossentropy 

## tf.nn.softmax_cross_entropy_with_logits

In [14]:
import tensorflow as tf

batch_size, nclass = 3, 4
logits = tf.random.truncated_normal([batch_size, nclass])
labels = tf.random.truncated_normal([batch_size, nclass])

# [batch_size]
softmax_ret = tf.nn.softmax_cross_entropy_with_logits(labels=labels, logits=logits)

with tf.Session() as sess:
    ret = sess.run(softmax_ret)
    print(ret) 

[-0.5096881  7.2809286  4.830508 ]


In [17]:
import tensorflow as tf
import numpy as np

batch_size, seq_len, nclass = 3, 4, 2
logits = tf.random.truncated_normal([batch_size, seq_len, nclass])
labels = tf.random.truncated_normal([batch_size, seq_len, nclass])


# [batch_size, seq_len]
softmax_ret = tf.nn.softmax_cross_entropy_with_logits(labels=labels, logits=logits)

with tf.Session() as sess:
    ret = sess.run(softmax_ret)
    print(ret) 

[[ 0.49649793  0.33734643 -0.36940873  0.24192703]
 [-0.98695374 -0.0262391   0.3136371  -1.5682083 ]
 [-0.3025692  -0.6598132  -1.4551672  -1.2052009 ]]


### mask

In [17]:
import tensorflow as tf

batch_size = 100
w0, w1 = 0.25, 0.57

# [batch_size, 2]
logits = tf.Variable(tf.random_normal(shape=(batch_size, 2), stddev=1.))

# [batch_size,]
y = tf.random_uniform(shape=(batch_size,), maxval=2, dtype=tf.int32)

loss_per_example = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=y)
weights = tf.where(tf.cast(y, tf.bool), tf.ones((batch_size,))*w0, tf.ones((batch_size,))*w1)

# weighted cost
loss = tf.reduce_mean(tf.multiply(loss_per_example, weights))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    loss_val = sess.run(loss)
    print(loss_val)

0.34863514


## sparse_softmax_cross_entropy_with_logits

### 三维

常常是序列标注任务。一个句子有多个单词，每个单词都有一个 label

In [18]:
import tensorflow as tf
import numpy as np

batch_size, seq_len, nclass = 2, 5, 4
logits = tf.random.truncated_normal([batch_size, seq_len, nclass])
labels = tf.constant(np.random.randint(0, nclass-1, [batch_size, seq_len]), tf.int64)

# [batch_size, seq_len]
softmax_op = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels, logits=logits)
with tf.Session() as sess:
    ret = sess.run([labels, softmax_op])
    print(ret[0])
    print(ret[1])

[[1 1 1 1 0]
 [2 0 0 2 2]]
[[2.6557298  0.9863844  0.8881042  1.8395048  2.4123902 ]
 [0.57340413 2.8348143  2.0145783  1.7515566  1.6782222 ]]
