[toc]

# Tensorflow onehot

In [3]:
import tensorflow as tf

onehot = tf.one_hot([1,2,3,4,1], depth=10)
with tf.Session() as sess:
    ret = sess.run(onehot)
    print(ret)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
