## tf.reduce_sum, tf.reduce_max

注意使用 axis 参数和 keepdims 参数

In [106]:
x1 = tf.constant([[1.0, 4.0],
                 [3.0, 2.0],
                 [4.0, 6.0]])    

# 默认是对所有的元素计算
tf.reduce_min(x1) # <tf.Tensor: shape=(), dtype=float32, numpy=1.0>

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [111]:
# axis=1 对行计算
tf.reduce_max(x1, axis=1) # <tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 3., 6.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 3., 6.], dtype=float32)>

In [110]:
# 保持维度 keepdims=True
tf.reduce_sum(x1, keepdims=True) # <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[10.]], dtype=float32)>

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[20.]], dtype=float32)>

In [1]:
import tensorflow as tf

`tf.keras.layers.Dense` 如果不指定 activation 时，激活函数为空