[toc]

# Tensorflow crossentropy 

In [14]:
import tensorflow as tf

batch_size, nclass = 3, 4
logits = tf.random.truncated_normal([batch_size, nclass])
labels = tf.random.truncated_normal([batch_size, nclass])

# [batch_size]
softmax_ret = tf.nn.softmax_cross_entropy_with_logits(labels=labels, logits=logits)

with tf.Session() as sess:
    ret = sess.run(softmax_ret)
    print(ret) 

[-0.5096881  7.2809286  4.830508 ]


In [17]:
import tensorflow as tf
import numpy as np

batch_size, seq_len, nclass = 3, 4, 2
logits = tf.random.truncated_normal([batch_size, seq_len, nclass])
labels = tf.random.truncated_normal([batch_size, seq_len, nclass])



# [batch_size, seq_len]
softmax_ret = tf.nn.softmax_cross_entropy_with_logits(labels=labels, logits=logits)

with tf.Session() as sess:
    ret = sess.run(softmax_ret)
    print(ret) 

[[ 0.49649793  0.33734643 -0.36940873  0.24192703]
 [-0.98695374 -0.0262391   0.3136371  -1.5682083 ]
 [-0.3025692  -0.6598132  -1.4551672  -1.2052009 ]]


## sparse_softmax_cross_entropy_with_logits

### 三维

常常是序列标注任务。一个句子有多个单词，每个单词都有一个 label

In [22]:
import tensorflow as tf
import numpy as np

batch_size, seq_len, nclass = 2, 5, 4
logits = tf.random.truncated_normal([batch_size, seq_len, nclass])
labels = tf.constant(np.random.randint(0, nclass-1, [batch_size, seq_len]), tf.int64)

# [batch_size, seq_len]
softmax_op = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels, logits=logits)
with tf.Session() as sess:
    ret = sess.run(softmax_op)
    print(ret)

[[3.3915517 3.1047626 3.2631962 1.1493012 3.0194685]
 [1.896068  2.0224884 2.1923144 2.168262  2.1832938]]
