[toc]

# Tensorflow argmax

In [7]:
import tensorflow as tf
import numpy as np


x = tf.constant(np.random.normal(size=(3,4,5)))
argmax = tf.argmax(x, axis=-1)

with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(argmax))

[[[ 0.51914843  0.79442973 -0.4826877   0.5712281  -2.89543088]
  [ 0.09910049  0.15006273  0.32682984  0.72683424 -0.87183461]
  [ 0.69824347 -0.319515    1.65889212  0.25629936 -0.30733939]
  [-2.01349167  2.49388557  1.64354943  0.490304   -0.8440264 ]]

 [[ 0.31558306 -0.02472891  0.47017108 -0.07395894  0.32197448]
  [-1.13058988  1.51426088 -2.21263398  0.09365468 -0.55756489]
  [-0.46100975  0.23125329  0.83979465  1.28642456 -1.79152317]
  [-0.6974488   0.3176169  -0.87279863  1.12678965 -1.35673979]]

 [[ 0.58211931  0.09599593  0.56847665 -0.05573308  0.53564008]
  [-0.2519064   0.29568329  1.04915223  0.20731    -0.49302051]
  [-1.24565129  0.09365373 -0.35010423  1.39989108  0.07878053]
  [ 0.2843332  -1.60750406 -0.81665672 -0.54402866 -0.76723619]]]
[[1 3 2 1]
 [2 1 3 3]
 [0 2 3 0]]
